### ISSUE TITLE
Erro when call nirs.scan()

### ISSUE THREAD

**Issue by ThiagoFurtado** [HighTemplar-wjiang/NIRScanner-Python#2]
Hi, 
when I call **scan()**, I'm getting the following error:

> Scan in progress. Estimated Scan time is approximately -0.001 seconds. Reading device status for scan completion failed.
> ERROR: Scan failed.
> Header version: 3067849444
> not a valid tpl file
> ERROR: Interpret data failed.

What can I do to solve this?

Thanks in advance.

**Comment by HighTemplar-wjiang** [comment]
Hi Thiago, 

From my experience, it ususally happens when the scanner does not detect enough lights. For example, it happens often in transmission mode if your sample (almost) completely absorbs the emitted lights. 

Sometimes setting the GPA gain to 64 may help, but you cannot expect a good spectrum. Also, do not forget to reset the scanner if an error happens.
