### ISSUE TITLE
Is it possible to have a 32bit arm compiled NIRScanner.so?

### ISSUE THREAD

**Issue by 12HuYang** [HighTemplar-wjiang/NIRScanner-Python#5]
Hi there,

I'm working with the NIR scanner with my beaglebone board. Since the board is ARM 32bit, so when I use your compiled .so document, it shows the wrong ELF class. Is it possible to have a 32bit compiled .so file?

I also looked at the DLPNIRNANOEVM GUI 2.10, but also can not compile with their compiled library in c.

Thanks,
Yang

**Comment by HighTemplar-wjiang** [comment]
Hi Yang, 

Yes, it is possible to run the library on a ARM 32-bit board. Please note the default .so file is for x86 Linux (64-bit), you should check the "Raspberry Pi with Python 2" section if you are using a ARM 32-bit board. 

The repository includes a pre-compiled **.so.2.pi** file for Raspberry Pi (ARM, 32-bit, little-ending). However, please note there are some OS related dependencies (I used it with **Noobs for Pi, Python 2.7**), you can have a try with your own board if you are running Linux with a similar kernel version. 

Otherwise, also recommended for compatibility, you can compile your own .so file following the instructions in README.

**Comment by 12HuYang** [comment]
Hi Wjiang,

Thank you for the explanation. I compiled the *.so file and it works well.

Thanks!

Yang Hu

**Comment by HighTemplar-wjiang** [comment]
Glad to know it works well, good luck to your project.
